#!/bin/bash
set -x
set -e

git push git@heroku.com:nichi-staging.git develop:master
heroku run rake db:migrate --app nichi-staging
heroku run rake db:seed --app nichi-staging
# bundle exec rake smoke:staging
